### ISSUE TITLE
M1 ponowienie platnosci

### ISSUE THREAD

**Issue by tomekjordan** [PayU/plugin_magento_2#1]
Sorry, ze tu, ale wersja M1 nie ma zakladki Issues. No nie ma od zawsze ponawiania platnosci. 
Brak tej opcji zdecydowanie wywoluje problemy, user musi klonowac zamowienie, tlumaczenia jak to zrobic zabieraja czas. czy do wersji M1 mozecie dodac Ponow Zamowienie? tak jak to jest w M2?

ps. nareszcie Wasz plugin jest dobrze pomyslany - widok metod platnosci na checkoucie plus pola do wpisania nr karty - tak to powinno od początku wygladac tez do M1 - czy mozecie plugin do M1 tak poprawic? ciagle 99% sklepow uzywa Magento 1 i ten plugin moglby byc tak dobrze pomyslany jak ten nowy.

dzieki
TJ

**Comment by regdos** [comment]
Zdajemy sobie sprawę, że ponowienie płatności to porządana funkcja ale aktualnie nie mamy zaplanowanych prac związanych z implementacją ponowień w Magento 1.

**Comment by tomekjordan** [comment]
To bardzo niedobrze, mowiac szczerze - nawet nie wiecie ile sklepow uzywa M1 czy M2 - bo podczas zakladania konta czy konta testowego - nie ma nawet Magento do wyboru. A Magento 1 bedzie przez 1-2 lata na pewno na >90% sklepow ciagle mialo. bo migracja na M2 jest droga i M2 ma bardzo liczne ciagle bugi. W skali Polski czy swiata - liczba instancji M2 jest marginalna - a to co widac na bulitwith.com to są zabawy developerow.
Dlatego naprawde prosze zeby jednak plugin do M1 mial te funkcji tak jak powinno to byc od poczatku
a) ponawianie platnosci - kazdy ecommerce to ma, oprocz Magento - a jak widac da sie to zrobic bo Paypal tak jest zrobiony, tak samo na waszym pluginie do M2 jest to zrobione.
b) wyswietlanie nr karty, CVV i daty wprost na checkoucie bez rediru.

z góry dziekki mimo wszystko licze ze uda sie to wprowadzic. bo pewnie to jest prosta sprawwa skoro to macie na M2. a konwersje w sklepach wzrosly by drastycznie - mam codziennie po pare telefonow i emaili ze nie moga uzyc kuponu jeszcze raz (bo kupon uzyty nawet w transakcji scancelowanej juz nie dziala) itp - i robią drugi raz zamowienie - a to jest wlasnie problem z ponawianiem 1 platnosci. ktory generuje X następnych.

pozdr
TJ

**Comment by regdos** [comment]
Dziękujemy za uwagi, zostały przekazane do osób odpowiedzialnych za rozwój produktów.
