### ISSUE TITLE
Brak podsumowania w mailach

### ISSUE THREAD

**Issue by mattkrupnik** [PayU/plugin_magento_2#14]
Hi,

Dlaczego w `vendor/payu/magento2-payment-gateway/Block/Sales/Order/Totals.php:18` jest `unset` na `$this->_totals['base_grandtotal']` wywołanie w `vendor/payu/magento2-payment-gateway/view/frontend/layout/sales_email_order_items.xml` w bloku `<block name="order_totals" class="PayU\PaymentGateway\Block\Sales\Order\Totals" template="Magento_Sales::order/totals.phtml" />` zabieg ten usuwa podsumowanie zamówienia w mailu.

Pozdrawiam
Mateusz

**Comment by regdos** [comment]
Potwierdzamy jest taki problem. To było zamierzone ale nie powinno to tak działać. Przygotujemy zmianę.

**Comment by mattkrupnik** [comment]
`return parent::_beforeToHtml();` jest pusty, podsumowanie się nie wyświetla

**Comment by mattkrupnik** [comment]
@regdos kiedy można spodziewać się fix'a?

**Comment by regdos** [comment]
Wrzuciłem poprawkę https://github.com/PayU/plugin_magento_2/commit/7962f340a5de82be77e892cf5c3723476a712da3 proszę sprawdzić czy teraz jest dobrze.
