### ISSUE TITLE
Emaile po transakcji Payu - sa popsute

### ISSUE THREAD

**Issue by tomekjordan** [PayU/plugin_magento_2#2]
Witam, po transkakcjach testowych w najnowszym Module do Magento 2 - wszystkie emaile transakcyjne są "zepsute"

Screenshot: [http://prntscr.com/hgkwu2](http://prntscr.com/hgkwu2)

Potwierdzenie zamowienia tez generuje pusty email z 1 linijką:
"Error filtering template: Element 'referenceBlock', attribute 'class': The attribute 'class' is not allowed. Line: 74"

pozdr
TJ

**Comment by regdos** [comment]
Wszystkie maile czy tylko mail o ponowieniu transakcji?
W ktorej wersji Magento problem występuje?

**Comment by tomekjordan** [comment]
transakcyjne. to znaczy email z jakims info o ponowieniu przyszedl pusty i z tym bledem i standardowy z zamowieniem magento tez jets pusty i taki sam bład
Magento 211

**Comment by regdos** [comment]
W standardowy mail w żaden sposób nie ingerujemy więc wygląda na problem po stronie Twojej instalacji Magneto.

**Comment by tomekjordan** [comment]
Dziwne, bo przed instalaja Payu - zrobilem testowe zamowienie i email byl prawidlowy. sprawdze po wylaczeniu pluginu i dam  znac.

**Comment by regdos** [comment]
Co wyszło ze sprawdzanie? Bo nie możemy tego zreplikować.

**Comment by regdos** [comment]
Przetestowaliśmy to wielokrotnie z Magento 2.1 i 2.2 i wszystko działa poprawnie, z braku odpowiedzi zamykam.

**Comment by tomekjordan** [comment]
Moge potwierdzic ze to nadal występuje - i testowalem to przed chwilą na M2.2.2 gołym.
Jeżeli moduł Payu jest włączony - to nie można utworzyć konta klienta, tak samo przy zamówieniu kiedy się nie jest zalogowanym - zamówienie jest zrobione (nie testowalem przejscia do Payu), ale na COD payment, a po takim zamówieniu otrzymuje dokladnie taki sam pusty email z tekstem "Error filtering template: Element 'referenceBlock', attribute 'class': The attribute 'class' is not allowed. Line: 74".

Dla jasnosci - instaluje gołe Magento 2.2.2 CE.
PHP 7.1
Maria DB 10.1
nic specjalnego tam nie ma. Po raz pierwszy ten bład wystąpił na M2.1.1 plus starsza wersja pluginu Payu. Teraz to samo występuje nadal na najnowszym Magento 2 i najnowszej wersji pluginu.

**Comment by tomekjordan** [comment]
@regdos dasz radę spojrzeć?
