### ISSUE TITLE
Support to ARS currency

### ISSUE THREAD

**Issue by mateo2181** [PayU/plugin_magento_2#23]
I want to know if the module has support to ARS currency.
I am working with Magento 2.2.5.
Thanks.

**Comment by lgrzesiak** [comment]
Hi, you have probably mistaken a plugin from PayU S.A. incorporated in Poland, a payment gateway processing transactions in the European Union with PayU in Argentina. This plugin cannot be used by shops incorporated in Argentina. For more info see: https://www.payulatam.com/ar/
