### ISSUE TITLE
problem przy zapisie płatności

### ISSUE THREAD

**Issue by devhero-tech** [PayU/plugin_magento_2#25]
Cześć, przy przechodzeniu procesu płatności w koszyku pojawia się błąd i nie przekierowuje do payu.
magento 2.2.6

`{
  message: "Transakcja została odrzucona. Prosimy spróbować ponownie później.",
  …
}message: "Transakcja została odrzucona. Prosimy spróbować ponownie później."trace: "#0 /Volumes/work/www/webpage/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Model\GuestPaymentInformationManagement->savePaymentInformationAndPlaceOrder('XXXXXXXXXX...', 'test@test...', Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))↵#1 /Volumes/work/www/webpage/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->___callParent('savePaymentInfo...', Array)↵#2 /Volumes/work/www/webpage/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->Magento\Framework\Interception{closure}('XXXXXXXXXXX...', 'test@test...', Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))↵#3 /Volumes/work/www/webpage/generated/code/Magento/Checkout/Model/GuestPaymentInformationManagement/Interceptor.php(26): Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->___callPlugins('savePaymentInfo...', Array, Array)↵#4 [internal function]: Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->savePaymentInformationAndPlaceOrder('XXXXXXXXXX...', 'test@test...', Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))↵#5 /Volumes/work/www/webpage/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)↵#6 /Volumes/work/www/webpage/vendor/magento/module-webapi/Controller/Rest.php(244): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process(Object(Magento\Framework\Webapi\Rest\Request\Proxy))↵#7 /Volumes/work/www/webpage/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))↵#8 /Volumes/work/www/webpage/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent('dispatch', Array)↵#9 /Volumes/work/www/webpage/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))↵#10 /Volumes/work/www/webpage/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(39): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)↵#11 /Volumes/work/www/webpage/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))↵#12 /Volumes/work/www/webpage/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()↵#13 /Volumes/work/www/webpage/vendor/magento/framework/App/Bootstrap.php(257): Magento\Framework\App\Http\Interceptor->launch()↵#14 /Volumes/work/www/webpage/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))↵#15 {main}"`

**Comment by regdos** [comment]
Na jakim etapie procesu zakupu pojawia się błąd. Jak powtórzyć ten błąd. 
Na pewno jest to błąd zwiażany z pluginem w PayU (w załączonych logach nie ma w stacktrace informacji o PayU)?

**Comment by devhero-tech** [comment]
prawdopodobnie było to spowodowane przez błąd w magento
