### ISSUE TITLE
struktura plikow +Composer > Packagist

### ISSUE THREAD

**Issue by tomekjordan** [PayU/plugin_magento_2#3]
Witam, dobrze by bylo zeby struktura plikow byla w 1 podkatalogu w app/code
bo teraz są takie kwiatki jak katalog app/i18n
co kompletnie powoduje zamieszanie w standardowej strukturze plikow magento

brakuje tez rejestracji dla Composera na Packagist..

dzięki

**Comment by maqlec** [comment]
Dołączam się do wniosku przedmówcy.
Ten plugin powinien być dostarczony tylko jako jego kod źródłowy a OpenPayu dostarczone jako zależność poprzez composer.

**Comment by tomekjordan** [comment]
z tym OpenPayu tylko w composerze to bym tak daleko nie poszedl. bo niektorzy instaluja rozszerzenia w M2 bez composera...

**Comment by regdos** [comment]
SDK OpenPayu chcemy mieć wewnątrz pluginu. 
Przygotujemy poprawkę wrzucającą wszystko do jednego katalogu. 
Packagista też przygotujemy.

**Comment by regdos** [comment]
https://packagist.org/packages/payu/magento2-payment-gateway
