### ISSUE TITLE
[Sandbox] Notyfikacje

### ISSUE THREAD

**Issue by jemoon** [PayU/plugin_magento_2#31]
Czy sandbox powinien poprawnie wysylac notyfikacje? Zauwazylem ze od jakiegos czasu (zdaje sie, ze w XII.2018 dzialalo to jeszcze beż problemu) wszystkie zktualizacje statusu koncza sie jak na zalaczonym screenie co niestety uniemozliwia sprawdzenie calego order flow :/

![image](https://user-images.githubusercontent.com/3430741/55031756-92d9f580-500f-11e9-9582-ae2d5f1effc2.png)

**Comment by regdos** [comment]
Czy sklep jest wystawiony przez Cloudflare?

**Comment by jemoon** [comment]
@regdos tak, to jest srodowisko testowe...

**Comment by regdos** [comment]
Trzeba w Cloudflare wyłączyć Browser Integrity Check 
Więcej informacji w zgłoszeniu https://github.com/PayU/plugin_magento/issues/70#issuecomment-418291664

**Comment by jemoon** [comment]
@regdos dzieki 👍
