### ISSUE TITLE
Repay email - domyslny store przekazany w opcjach templatki

### ISSUE THREAD

**Issue by jemoon** [PayU/plugin_magento_2#32]
Przekazanie domyslnego store'a podczas budowania templatki mailowej dla powiadomienia o mozliwosci oplacenia zamowienia ponownie powoduje wyswietlenie w mailu transakcyjnym nieprawidlowych grafik np. logo.

**Comment by regdos** [comment]
https://github.com/PayU/plugin_magento_2/releases/tag/v1.2.8
