### ISSUE TITLE
problem z odbiorem płatności z payu

### ISSUE THREAD

**Issue by devhero-tech** [PayU/plugin_magento_2#34]
ID płatności: 1317974914
w panelu payu pojawia się jako przyjęta, w logach informacja:
code (ERROR): 302, Response: "", czasami uda się wywołać 
code (ERROR): 421, Response: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>421 Misdirected Request</title> </head><body> <h1>Misdirected Request</h1> <p>The client needs a new connection for this request as the requested host name does not match the Serv"

**Comment by regdos** [comment]
Wygląda na problem z konfiguracją magento ponieważ żądanie POST na adres notyfikacji zwraca przekierowanie na stronę główną sklepu.

**Comment by devhero-tech** [comment]
jak nie ustawię magento to i tak lecą redirecty ;] Może Warto by w dokumentacji zawrzeć zalecaną konfigurację, bo przy podstawowej instalacji dzieje się to za każdym razem.

**Comment by regdos** [comment]
Zawsze testujemy w domyślnej konfiguracji i nie mamy problemu. Inne osoby korzystające z pluginu nie zgłaszają takiego problemu. To jest pierwsze zgłoszenie. 
Może jest jakaś dodatkowa konfiguracja na poziomie apache, itp.?

**Comment by devhero-tech** [comment]
Problem w tym, że zainstalowałem golasa + payu, GET'em ruta przechodzi, post przekierowuje do strony głównej, sprawdzam insomnią ( wklejam zwrotkę jako body ) i post jest przekierowywany na główną i nawet nie dotyka paczki. Nie ma też w integracji nigdzie deklaracji, że jest obsługiwana POST'em

**Comment by devhero-tech** [comment]
Cześć, analizuję ten przypadek. Wygląda na to, że od wersji 2.3.x Paczka payu nie jest przystosowana. POSTy są przekierowywane na home, GETy przechodzą bez problemu ( pomijam puste body itd) . Prawdopodobne obejście problemu: https://magento.stackexchange.com/questions/253414/magento-2-3-upgrade-breaks-http-post-requests-to-custom-module-endpoint

**Comment by devhero-tech** [comment]
Przeciążenie controllera i dorzucenie CsrfAwareActionInterface rozwiązuje problem. Magento z tego co widzę wymaga csrf tokena dla wszystkich POSTów (oprócz autoryzowanego dostępu do api), więc siłą rzeczy odrzuca request od Was.

**Comment by regdos** [comment]
To sprawa jasne. Dla M2.3 jest osobna wersja pluginu https://github.com/PayU/plugin_magento_23

**Comment by devhero-tech** [comment]
Dzięki ;) niech zostanie dla potomnych
