### ISSUE TITLE
Zasady składania zamówień

### ISSUE THREAD

**Issue by stalica** [PayU/plugin_magento_2#4]
W obu metodach płatności nie pojawiają się zdefiniowane warunki w zasadach składania zamówienia.

Zapomnieliście wdrożyć czy ja czegoś nie widzę?

**Comment by regdos** [comment]
Przyznam, że nie rozumiem o co pytasz. 
Co to są "zdefiniowane warunki w zasadach składania zamówienia."?

**Comment by stalica** [comment]
Chodzi oczywiście o funkcjonalność: Stores -> Terms and Conditions.

**Comment by regdos** [comment]
Fix: https://github.com/PayU/plugin_magento_2/commit/fde12922f2a3c215a2ae933dbdf9cbe423a6ce5f
