### ISSUE TITLE
Sandbox - links etc problemy w v.1.1.0

### ISSUE THREAD

**Issue by tomekjordan** [PayU/plugin_magento_2#6]
Witam, przy instalacji najnowszej wersji pluginu 1.1.0

1. link do setting sandboxa daje pusty ekran: [http://prntscr.com/hock22](http://prntscr.com/hock22)
https://registration-merch-prod.snd.payu.com/boarding/#/form&pk_campaign=Plugin&pk_kwd=Magento2?_k=apf2ap
2. link otwiera okienko zastępujac glowne okno Magento - chyba powinno otwierca link jako _blank ..?
3. "If you do not already have PayU merchant account, please register in Production or please register in Production" [http://prntscr.com/hocl2m](http://prntscr.com/hocl2m) Chyba coś tu jest nie halo....

pozdr
TJ

**Comment by regdos** [comment]
Fix https://github.com/PayU/plugin_magento_2/commit/af9f91a7a8ca254826ef89bd8a655d45d54e3d9b
