### ISSUE TITLE
Błąd w strukturze pliku XML layoutu: customer_account_index.xml; The attribute 'class' is not allowed

### ISSUE THREAD

**Issue by dudzio12** [PayU/plugin_magento_2#8]
`Element 'referenceBlock', attribute 'class': The attribute 'class' is not allowed. Line: 922`

Od wersji 2.2.0, nie jest dozwolone użycie atrybutu "class" w elemencie "referenceBlock".

`<referenceBlock name="customer_account_dashboard_top" class="PayU\PaymentGateway\Block\Order\Recent">(...)</referenceBlock>`

Takie użycie występuje w pliku `view/frontend/layout/customer_account_index.xml`.
Błąd uniemożliwia przejście w skecję użytkownika: /customer/account.

Więcej o problemie tutaj: https://github.com/magento/magento2/issues/11116.

**Comment by dudzio12** [comment]
Również w plikach:
`view/frontend/layout/sales_email_order_items.xml`,
`view/frontend/layout/sales_order_history.xml`,
`view/frontend/layout/sales_order_view.xml`

**Comment by tomekjordan** [comment]
to jest pewnie przyczyna błędów ktore ja wczesniej wskazalem > 
[https://github.com/PayU/plugin_magento_2/issues/2](https://github.com/PayU/plugin_magento_2/issues/2)
ticket jest zamknięty - ale dopisalem loga ktory pokazuje - ze jest cos nie tak z Payu dla M2

**Comment by dudzio12** [comment]
Dokładnie tak

**Comment by regdos** [comment]
@tomekjordan tak. Pracuję nad poprawką.

**Comment by regdos** [comment]
Poprawka https://github.com/PayU/plugin_magento_2/commit/7483c430854e58c85b4970658fab4ad1b715d3a6 
Testowane na wersji 2.1.9 i 2.2.1 i działa poprawnie.

**Comment by dudzio12** [comment]
@regdos - Potwierdzam, że w /customer/account/ nie ma już błędu.
